-- Sessions table
CREATE TABLE sessions (
  session_id UUID PRIMARY KEY, -- Cookie/session ID
  avatar_url TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL
);

-- Posts table
CREATE TABLE posts (
  post_id UUID PRIMARY KEY, -- UUID generated by Go app
  session_id UUID NOT NULL REFERENCES sessions(session_id), -- changed TEXT -> UUID to match FK type
  user_name TEXT NOT NULL DEFAULT 'Anonymous',
  post_title TEXT NOT NULL,
  post_content TEXT, -- Removed "NULLABLE" (not valid SQL)
  image_urls TEXT[] DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_archived BOOLEAN DEFAULT FALSE
);

-- Comments table
CREATE TABLE comments (
  comment_id UUID PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
  session_id UUID NOT NULL REFERENCES sessions(session_id), -- changed TEXT -> UUID to match FK
  user_name TEXT NOT NULL DEFAULT 'Anonymous',
  comment_content TEXT,
  parent_comment_id UUID REFERENCES comments(comment_id),
  image_urls TEXT[] DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_archived BOOLEAN DEFAULT FALSE
);

-- Indexes
CREATE INDEX idx_posts_session_id ON posts(session_id);
CREATE INDEX idx_posts_created_at ON posts(created_at);
CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_parent ON comments(parent_comment_id);
