package model

import "time"

type UUID = string // shortcut, will be generated by GenerateUUID

type Comment struct {
	CommentID       UUID
	PostID          UUID
	SessionID       UUID
	Content         string
	ParentCommentID *UUID
	ImageURLs       []string
	CreatedAt       time.Time
	IsArchived      bool
}
