package model

import (
	"1337b04rd/pkg/utils"
	"time"
)

type UUID = string // shortcut, will be generated by GenerateUUID

type Comment struct {
	CommentID       utils.UUID
	PostID          utils.UUID
	SessionID       utils.UUID
	UserName        string
	Content         string
	ParentCommentID utils.UUID
	ImageURLs       []string
	CreatedAt       time.Time
	IsArchived      bool
}
